"""Table-driven tests for scripts/validate.py.

Run with: uv run --with pytest pytest tests/
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "validate.py"


def run(message: str, *args: str):
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        input=message,
        capture_output=True,
        text=True,
        check=False,
    )
    out = json.loads(proc.stdout) if proc.stdout.strip() else {}
    return proc.returncode, out, proc.stderr


@pytest.mark.parametrize(
    "msg",
    [
        "feat: added a login form\n",
        "fix(auth): fixed token refresh\n",
        "impr(skill): tightened gotchas section\n\n- Added clearer rules.\n- Bumped version.\n",
        "feat(api/v2): introduced new endpoint\n",
    ],
)
def test_valid_messages(msg):
    code, out, _ = run(msg)
    assert code == 0
    assert out == {"ok": True}


def test_empty_is_invalid():
    code, out, _ = run("")
    assert code == 1
    assert any(e["code"] == "empty" for e in out["errors"])


def test_summary_too_long():
    code, out, _ = run("feat: this is way way way way way too many words here\n")
    assert code == 1
    assert any(e["code"] == "summary_too_long" for e in out["errors"])


def test_summary_max_override_passes():
    code, out, _ = run(
        "feat: one two three four five six seven eight nine\n",
        "--summary-max", "9",
    )
    assert code == 0
    assert out == {"ok": True}


def test_body_too_long():
    body_words = " ".join(["word"] * 31)
    code, out, _ = run(f"feat: did a thing\n\n{body_words}\n")
    assert code == 1
    assert any(e["code"] == "body_too_long" for e in out["errors"])


def test_disallowed_type():
    code, out, _ = run("nope: something happened\n")
    assert code == 1
    assert any(e["code"] == "type_disallowed" for e in out["errors"])


def test_invalid_scope_or_malformed_header():
    code, out, _ = run("feat(Bad Scope): did things\n")
    assert code == 1
    codes = {e["code"] for e in out["errors"]}
    assert codes & {"scope_invalid", "header_malformed"}


def test_ai_attribution_blocked_gemini():
    code, out, _ = run("feat: added auth helper\n\nGenerated by Gemini.\n")
    assert code == 1
    assert any(e["code"] == "ai_attribution" for e in out["errors"])


def test_ai_attribution_blocked_phrase():
    code, out, _ = run("feat: added auth helper\n\nAuthored by an AI assistant.\n")
    assert code == 1
    assert any(e["code"] == "ai_attribution" for e in out["errors"])


def test_missing_blank_line():
    code, out, _ = run("feat: did a thing\nsecond line is not blank\n")
    assert code == 1
    assert any(e["code"] == "missing_blank_line" for e in out["errors"])


def test_usage_error_unreadable_file():
    code, _, _ = run("doesnt matter", "--file", "/nonexistent/path/here.msg")
    assert code == 2


def test_errors_carry_fix_field():
    code, out, _ = run("feat: this is way way way way way too many words here\n")
    assert code == 1
    for err in out["errors"]:
        assert "fix" in err and err["fix"]
